insert into allclean.imagenes values
(default, "cocina1.webp",1),
(default,"cocina15.webp",2),
(default, "desinfect1.webp",3),
(default, "otros5.webp",4),
(default, "otros1.webp",5),
(default, "cocina5.webp",6),
(default, "banio1.webp",7),
(default, "banio2.webp",8),
(default, "banio3.webp",9),
(default, "banio4.webp",10),
(default, "banio5.webp",11),
(default, "banio6.webp",12),
(default, "banio7.webp",13),
(default, "banio8.webp",14),
(default, "banio9.webp",15),
(default, "cocina2.webp",16),
(default, "cocina3.webp",17),
(default, "cocina4.webp",18),
(default, "cocina6.webp",19),
(default, "cocina7.webp",20),
(default, "cocina8.webp",21),
(default, "cocina9.webp",22),
(default, "cocina10.webp",23),
(default, "cocina11.webp",24),
(default, "pisosymuebles1.webp",25),
(default, "pisosymuebles2.JPG",26),
(default, "pisosymuebles3.webp",27),
(default, "pisosymuebles4.webp",28),
(default, "pisosymuebles5.webp",29),
(default, "otros.webp",30),
(default, "otros2.webp",31),
(default, "otros3.webp",32),
(default, "otros4.webp",33),
(default, "otros6.webp",34),
(default, "otros7.webp",35),
(default, "otros8.webp",36),
(default, "otros9.webp",37),
(default, "cocina12.webp",38),
(default, "desinfect2.webp",39),
(default, "desinfect3.webp",40),
(default, "otros2.webp",41),
(default, "otros3.webp",42),
(default, "otros4.webp",43),
(default, "otros6.webp",44),
(default, "otros7.webp",45),
(default, "otros8.webp",46),
(default, "otros9.webp",47),
(default, "cocina12.webp",48),
(default, "desinfect2.webp",49),
(default, "desinfect3.webp",50)


	